(in-package :xvmasm)

(defconstant +revision+ 7 "xvmasm revision number")
(defparameter *build-options* nil)

(defparameter *start-point* 0)
(defparameter *token-stream* nil)
(defparameter *instruction-stream* nil)
(defparameter *stage2-inst-stream* nil)
(defparameter *datastream* nil)
(defparameter *labels* nil)
(defparameter *defines* nil)
(defparameter *curline* 0)
(defparameter *curfile* "MAIN")
(defparameter *total-lines* 0)
(defparameter *total-instructions* 0)
(defparameter *total-bytes* 0)
(defparameter *loaded-files* nil)
(defparameter *total-files* 0)
(defparameter *preprocessor-plugins* nil)
(defparameter *print-files* nil)
(defparameter *print-stats* nil)
(defparameter *allow-plugins* t)
(defparameter *error-on-plugin-load* nil)
(defparameter *error-on-warning* nil)
