(in-package :xvmasm)

(defvar testinsts '("    mov r0,r1"
		    "    ldc r2,0x1234"
		    "    ld r5,0x4567"
		    "    ldr r5,r6"
		    "    ldi r6,0x4567"
		    "main:"
		    "    mov r7,r6"
		    "    outr r6,r7"
		    ".sub1:"
		    "    jmp @main"
		    "    jmp @.sub1"
		    "main2:"
		    "    mov r8,r9"
		    ".sub1:"
		    "    inr r0,r1"
		    ".sub2:"
		    "    out.w 0xabcd,r1"
		    ".sub3:"
		    "    out.h 0xef01,fp"
		    ".sub4:"
		    "    inr.b r5,r1"
		    "main3:"
		    "    add r0,r1"
		    "    add r1,r2"
		    "    add r2,r3"
		    ".done:"
		    "    halt"
		    "    jmp @.done"))
