# geninstsc.awk -- generates insts.c from ILIST

BEGIN {
	tinst = 0
	printf "// xvm insts.c\n"
	printf "// autogenerated file! do not edit!\n\n"
	printf "#include <u.h>\n"
	printf "#include <cpu.h>\n"
	printf "#include <insts.h>\n"
	printf "\n"
	printf "Instdef	instdefs[] = {\n"
}

$1 == "revision" {
	printf "// microcode revision %s\n", $2
}

$1 != "#" && $0 != "" && $1 != "revision" {
	printf "\t{ %s, %s, %s, %s, %s, %s, %s },\n", $3, $4, $5, toupper($1), $6, $7, $8
	tinst = tinst + 1
}

END {
	printf "}; // %s instructions processed\n\n", tinst
}

