# geninstsh.awk -- generates insts.h from ILIST

BEGIN {
	tinst = 0
	printf "// xvm insts.h\n"
	printf "// autogenerated file! do not edit!\n"
	printf "\nenum {\n"
}

$1 == "#" { }

$1 != "#" && $0 != "" {
	printf "\t%s = %s,\n", toupper($1), $2
	tinst = tinst + 1
}

END {
	printf "}; // %s instructions processed\n\n", tinst
}

