# genregslisp.awk

BEGIN {
	tregs = 0
	printf ";;; autogenerated file! do not edit!\n\n"
	printf "(in-package :xvmasm)\n\n"
	printf "(defparameter *reg-list*\n"
	printf "  '("
}

$1 != "#" && $0 != "" {
	if(tregs != 0){
		printf "\n    "
	}
	printf"(:NAME %s :STRING \"%s\" :VALUE %s)", toupper($1), toupper($1), $2
	tregs = tregs + 1
}

END {
	printf "))\n"
	printf ";;; %s registers processed\n", tregs
}

