(in-package :xvm)

(definstruction sr (:args 2 :cycles 1 :use-width nil :use-mode nil)
  (let ((a (register cpu (car args)))
	(b (register cpu (cadr args)))
	(tmp 0))
    (setf tmp (ash a (* b -1))
	 (register cpu (car args)) (u32int tmp))
    (if (typep tmp 'u32int)
	(setf (flag cpu 9) 0)
	(setf (flag cpu 9) 1))))

(definstruction sl (:args 2 :cycles 1 :use-width nil :use-mode nil)
  (let ((a (register cpu (car args)))
	(b (register cpu (cadr args)))
	(tmp 0))
    (setf tmp (ash a b)
	  (register cpu (car args)) (u32int tmp))
    (if (typep tmp 'u32int)
	(setf (flag cpu 9) 0)
	(setf (flag cpu 9) 1))))

(definstruction not (:args 1 :cycles 1 :use-width nil :use-mode nil)
  (setf (register cpu (car args)) (u32int (lognot (register cpu (car args))))))

(definstruction and (:args 2 :cycles 1 :use-width nil :use-mode nil)
  (let ((a (register cpu (car args)))
	(b (register cpu (cadr args))))
    (setf (register cpu (car args)) (u32int (logand a b)))))

(definstruction or (:args 2 :cycles 1 :use-width nil :use-mode nil)
  (let ((a (register cpu (car args)))
	(b (register cpu (cadr args))))
    (setf (register cpu (car args)) (u32int (logior a b)))))

(definstruction xor (:args 2 :cycles 1 :use-width nil :use-mode nil)
  (let ((a (register cpu (car args)))
	(b (register cpu (cadr args))))
    (setf (register cpu (car args)) (u32int (logxor a b)))))
